FROM python:3.7-slim-buster
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 PYTHONUNBUFFERED=1 PYTHONDONTWRITEBYTECODE=1

RUN groupadd -r flaskg
RUN useradd --no-log-init -r -g flaskg flask

RUN apt-get update
RUN apt-get -yq upgrade
RUN apt-get -yq install gcc musl-dev linux-headers-amd64
RUN apt-get clean

RUN pip install --upgrade pip

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN rm requirements.txt

COPY app /usr/app

COPY raw_data/digits_db_dataset.npz /usr/digits_db_dataset.npz
COPY raw_data/fashion_db_dataset.npz /usr/fashion_db_dataset.npz

COPY populate_db.py /usr/populate_db.py

COPY migrations /usr/migrations


RUN chown -R flask:flaskg /usr/app
RUN chown -R flask:flaskg /usr/digits_db_dataset.npz
RUN chown -R flask:flaskg /usr/fashion_db_dataset.npz
RUN chown -R flask:flaskg /usr/populate_db.py
RUN chown -R flask:flaskg /usr/migrations

WORKDIR /usr/

USER flask
